#!/usr/bin/env python3
"""
Verify that the revenue calculation logic is properly implemented
"""
import pandas as pd
import re

def verify_revenue_calculation():
    """Verify the revenue calculation logic"""
    print("Verifying revenue calculation logic...")
    print("="*50)
    
    # Load the data
    df = pd.read_csv("data/database_data.csv")
    print(f"Loaded {len(df)} records from database_data.csv")
    
    # Show unique agents
    agents = df['agentName'].unique()
    print(f"Agents found: {list(agents)}")
    
    # Test the specific revenue calculation logic
    agent_name = "Mukilan"
    
    # Filter for specific agent and exclude declined orders
    agent_data = df[(df['agentName'] == agent_name) & (df['status'] != 'Declined')].copy()
    print(f"\nAgent {agent_name} - Valid orders (not declined): {len(agent_data)}")
    
    # Convert to numeric and calculate revenue
    agent_data['quantity_num'] = pd.to_numeric(agent_data['quantity'], errors='coerce')
    agent_data['rate_num'] = pd.to_numeric(agent_data['rate'], errors='coerce')
    agent_data['revenue'] = agent_data['quantity_num'] * agent_data['rate_num']
    agent_revenue = agent_data['revenue'].sum()
    
    print(f"Revenue for {agent_name}: ${agent_revenue:,.2f}")
    
    # Test for all agents
    print("\nTesting all agents revenue calculation...")
    valid_data = df[df['status'] != 'Declined'].copy()
    valid_data['quantity_num'] = pd.to_numeric(valid_data['quantity'], errors='coerce')
    valid_data['rate_num'] = pd.to_numeric(valid_data['rate'], errors='coerce')
    valid_data['revenue'] = valid_data['quantity_num'] * valid_data['rate_num']
    
    agent_revenues = valid_data.groupby('agentName')['revenue'].sum().sort_values(ascending=False)
    
    print("Revenue by all agents (excluding declined orders):")
    for agent, revenue in agent_revenues.items():
        print(f"  {agent}: ${revenue:,.2f}")
    
    print(f"\nTotal revenue: ${agent_revenues.sum():,.2f}")
    
    # Verify regex patterns work
    print("\nTesting regex patterns for revenue queries...")
    
    test_questions = [
        "What is the revenue generated by Mukilan?",
        "revenue generated by Devaraj",
        "Show revenue for agent Boopalan",
        "revenue by all agents",
        "What is the revenue generated by all agents?"
    ]
    
    for question in test_questions:
        question_lower = question.lower()
        
        # Check for agent-specific revenue query
        agent_match = re.search(r'for agent ([\w\s]+?)(?:\s|$)|for ([\w\s]+?) agent|([A-Za-z\s]+?)(?:\'s|s\') revenue|revenue for ([A-Za-z\s]+?)$|revenue generated by ([A-Za-z\s]+?)$|revenue by ([A-Za-z\s]+?)$', question_lower)
        revenue_by_agent_match = re.search(r'revenue generated by ([A-Za-z\s]+?)$|revenue by ([A-Za-z\s]+?)$|agent ([A-Za-z\s]+?) revenue', question_lower)
        
        print(f"Question: '{question}'")
        if agent_match:
            agent_name_match = next((g for g in agent_match.groups() if g and g not in ["'s", "s'"]), None)
            print(f"  -> Agent match found: {agent_name_match}")
        if revenue_by_agent_match:
            agent_name_match = next((g for g in revenue_by_agent_match.groups() if g and g not in ["'s", "s'"]), None)
            print(f"  -> Revenue by agent match: {agent_name_match}")
        if 'revenue generated by all agents' in question_lower or 'revenue by all agents' in question_lower or 'all agents revenue' in question_lower:
            print(f"  -> All agents revenue query detected")
        print()
    
    print("Revenue calculation logic verification completed successfully!")

if __name__ == "__main__":
    verify_revenue_calculation()